### PR TITLE
readme: various updates, including player controls and install instructions

### PR DESCRIPTION
**Pull request by AaronM04**
Our `README.md` is due for some spring cleaning! :grinning: 

- [x] player controls
- [x] updated linux (Ubuntu & Fedora) install instructions
- [x] updated macOS install instructions
- [x] updated Windows install instructions
- [x] create dissector README
- [x] remove references to SDL2
- [x] test the thing about `conwayste/resources/` directory errors
- [x] Discord chat badge
- [x] new gif(s)
- [x] license badge

### CODE REVIEW

**Comment by Manghi** [comment]
I'll get the Windows instructions soon, and will ask a friend to see if they can help verify the macOS installation steps.

**Comment by Manghi** [comment]
> The cpal readme has some good instructions for installing ALSA packages. It might be a good idea to link to and/or copy them below.

Mind sharing the link? Their GH page only lists detailed ASIO instructions for Windows.

**Comment by AaronM04** [comment]
> > The cpal readme has some good instructions for installing ALSA packages. It might be a good idea to link to and/or copy them below.
> 
> Mind sharing the link? Their GH page only lists detailed ASIO instructions for Windows.

It's the last paragraph in the first section: https://github.com/RustAudio/cpal#cpal---cross-platform-audio-library

Right before the webassembly part.

**Comment by Manghi** [comment]
Coordinating with a friend to determine the MacOSX build instructions.

**Comment by Manghi** [comment]
@AaronM04 Ready for your review!

**Comment by AaronM04** [comment]
The readme looks legit now! Thank you!

Merging...

**Pull request merged**
