### PR TITLE
Net: fix time in ping filter error message

### PR DESCRIPTION
**Pull request by AaronM04**
This is not a big deal but I just wanted to make a PR for this bug that jumped out at me. 😀 

Ready for review!

### CODE REVIEW

**Review by Manghi — APPROVED** [review]
Ah great catch! My only suggestion would be to keep the division of `seconds.millis.micro` as it's a little easier to digest with the period as the delimiter.

**Comment by AaronM04** [comment]
I would much rather have just a single decimal point. How about just milliseconds and no more digits?

**Comment by Manghi** [comment]
Let's keep it the way it currently is in the PR then. I prefer the higher resolution timestamp.

OK2Merge!

**Comment by AaronM04** [comment]
TYVM!

**Pull request merged**
