### PR TITLE
First rev for Configuration File `conwayste.toml`

### PR DESCRIPTION
**Pull request by Manghi**
Saves resolution, fullscreen mode, zoom level. Others TBD
Still needs error handling on file operations
Cleaned up unnecessary comments and build messages
Added in Copyright to other files

### CODE REVIEW

**Comment by Manghi** [comment]
I pushed the updated value to master but didn't catch this during conflicts. Thanks Aaron.
Make sure you delete `conwayste.toml` (ggez settings) as that is not compatible with this change.

**Comment by AaronM04** [comment]
@Manghi I deleted `conwayste.toml` and it runs now. However, I noticed it's super zoomed out and I can't zoom back in. Is there anything you can do to fix that before this gets merged in?

**Comment by Manghi** [comment]
I pushed the updated value to master but didn't catch this during conflicts. Thanks Aaron.
Make sure you delete `conwayste.toml` (ggez settings) as that is not compatible with this change.

**Comment by Manghi** [comment]
@AaronM04  That is because I can't type. Fixed and tested in latest commit.

**Comment by AaronM04** [comment]
@Manghi I pulled, deleted `conwayste.toml`, and ran it again, but it still has the problem: [https://imgur.com/6Z8uhmI](https://imgur.com/6Z8uhmI)

Any idea what's going on?

**Comment by Manghi** [comment]
Huh, strange.

I did a clean clone and checkout and it works. You're using -/+ to zoom right?
https://webmshare.com/AXdgy

**Comment by AaronM04** [comment]
I think this relates to our laptops' different available resolutions in SDL.

I manually changed `zoom = 5` to `zoom = 10` in conwayste.toml, and now it looks the same as in the master branch. I'm going to merge this and we can think about how to better pick the zoom value some other time.

Great work! 👍

**Pull request merged**
