### PR TITLE
Dissector setup & readme update

### PR DESCRIPTION
**Pull request by Manghi**
Added instructions to setup the dissector from a blank system.

- [x] Update to latest version of Wireshark (3.2)
- [x] Generalize installation instructions
- [x] Use `pkg_config` to get the `wireshark` and `glib2` headers
- [x] Use `pkg_config` to get the `glibconfig.h` header from the native header location (mine is `x86_64-linux-gnu`)

### CODE REVIEW

**Comment by AaronM04** [comment]
Tremendous! :100: 

For the CI, we could do one of two things:
* exclude this crate so it doesn't keep failing
* install everything CI is looking for

For the second one, one thing to do would be to update the docker image at https://hub.docker.com/r/aaronm04/cross/tags  This is probably the easiest part of getting CI to work lol.

**Comment by Manghi** [comment]
Merging `master` into this branch seemed to turn off the CI builds. Still digging into why. In any case, I think the package issue of wireshark and glib2 should be installed for Linux, and excluded for Windows.

Ready for final your review!

**Comment by AaronM04** [comment]
Thanks! Re: the CI builds, I see Appveyor but not Travis in my uicontext branch. I was hoping for the opposite lol

On March 3, 2020 7:18:07 PM PST, Manghi <notifications@github.com> wrote:
>Merging `master` into this branch seemed to turn off the CI builds.
>Still digging into why. In any case, I think the package issue of
>wireshark and glib2 should be installed for Linux, and excluded for
>Windows.
>
>Ready for final your review!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/conwayste/conwayste/pull/102#issuecomment-594303768

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AaronM04** [comment]
@Manghi Nice work!

Next time, please point it out if the base of the PR is not `master`. That threw me for a loop at first. :sweat_smile:  I think you can just do work directly in that branch if you want. If you want to change the name to `mang/dissector` that can be done as well -- just delete the `aaron/dissector` branch.

Also there are a few check boxes not checked. Do those need to be checked?

And what files should I be reviewing? I think this is showing a lot of files because master was not merged into `aaron/dissector` first.

**Comment by AaronM04** [comment]
I am working on updating the dockerfile used by `cross` so that it has these new packages. I just pushed it to https://github.com/conwayste/ci-docker in case you want to take a look.

My current stumbling block is getting debconf to answer my questions without a working terminal (no terminal available during `docker build`):

```
Configuring wireshark-common
----------------------------

Dumpcap can be installed in a way that allows members of the "wireshark" system
group to capture packets. This is recommended over the alternative of running
Wireshark/Tshark directly as root, because less of the code will run with
elevated privileges.

For more detailed information please see
/usr/share/doc/wireshark-common/README.Debian.

Enabling this feature may be a security risk, so it is disabled by default. If
in doubt, it is suggested to leave it disabled.

Should non-superusers be able to capture packets? [yes/no] 
```
^^^ can't answer that :sob:

**Comment by AaronM04** [comment]
Looks great! *prepare for PR landing*

**Pull request merged**
