### PR TITLE
Extend Widget Dimensional API

### PR DESCRIPTION
**Pull request by Manghi**
Per your request :smile: 
See #81 for details

`layer.rs` was updated to get this compiling, but the updates will be removed once #83 is merged

### CODE REVIEW

**Comment by AaronM04** [comment]
Please merge from master and resolve conflicts!

**Comment by Manghi** [comment]
Done!

**Comment by AaronM04** [comment]
Woot!

**Comment by AaronM04** [comment]
un-woot

**Comment by AaronM04** [comment]
> Woot!

woot is back

**Pull request merged**
